"use strict";

module.exports = function (environment) {
  const ENV = {
    modulePrefix: "ember-ebau-gwr",
    environment,
    // municipalities: {[sz|be|ur]: [{id: number, name: string}]}
    municipalities: {
      SZ: [
        { id: 1311, name: "Gersau" },
        { id: 1321, name: "Feusisberg" },
        { id: 1322, name: "Freienbach" },
        { id: 1323, name: "Wollerau" },
        { id: 1331, name: "Küssnacht (SZ)" },
        { id: 1341, name: "Altendorf" },
        { id: 1342, name: "Galgenen" },
        { id: 1343, name: "Innerthal" },
        { id: 1344, name: "Lachen" },
        { id: 1345, name: "Reichenburg" },
        { id: 1346, name: "Schübelbach" },
        { id: 1347, name: "Tuggen" },
        { id: 1348, name: "Vorderthal" },
        { id: 1349, name: "Wangen (SZ)" },
        { id: 1361, name: "Alpthal" },
        { id: 1362, name: "Arth" },
        { id: 1363, name: "Illgau" },
        { id: 1364, name: "Ingenbohl" },
        { id: 1365, name: "Lauerz" },
        { id: 1366, name: "Morschach" },
        { id: 1367, name: "Muotathal" },
        { id: 1368, name: "Oberiberg" },
        { id: 1369, name: "Riemenstalden" },
        { id: 1370, name: "Rothenthurm" },
        { id: 1371, name: "Sattel" },
        { id: 1372, name: "Schwyz" },
        { id: 1373, name: "Steinen" },
        { id: 1374, name: "Steinerberg" },
        { id: 1375, name: "Unteriberg" },
      ],
      BE: [
        { id: 301, name: "Aarberg" },
        { id: 302, name: "Bargen (BE)" },
        { id: 303, name: "Grossaffoltern" },
        { id: 304, name: "Kallnach" },
        { id: 305, name: "Kappelen" },
        { id: 306, name: "Lyss" },
        { id: 307, name: "Meikirch" },
        { id: 309, name: "Radelfingen" },
        { id: 310, name: "Rapperswil (BE)" },
        { id: 311, name: "Schüpfen" },
        { id: 312, name: "Seedorf (BE)" },
        { id: 321, name: "Aarwangen" },
        { id: 322, name: "Auswil" },
        { id: 323, name: "Bannwil" },
        { id: 324, name: "Bleienbach" },
        { id: 325, name: "Busswil bei Melchnau" },
        { id: 326, name: "Gondiswil" },
        { id: 329, name: "Langenthal" },
        { id: 331, name: "Lotzwil" },
        { id: 332, name: "Madiswil" },
        { id: 333, name: "Melchnau" },
        { id: 335, name: "Oeschenbach" },
        { id: 336, name: "Reisiswil" },
        { id: 337, name: "Roggwil (BE)" },
        { id: 338, name: "Rohrbach" },
        { id: 339, name: "Rohrbachgraben" },
        { id: 340, name: "Rütschelen" },
        { id: 341, name: "Schwarzhäusern" },
        { id: 342, name: "Thunstetten" },
        { id: 344, name: "Ursenbach" },
        { id: 345, name: "Wynau" },
        { id: 351, name: "Bern" },
        { id: 352, name: "Bolligen" },
        { id: 353, name: "Bremgarten bei Bern" },
        { id: 354, name: "Kirchlindach" },
        { id: 355, name: "Köniz" },
        { id: 356, name: "Muri bei Bern" },
        { id: 357, name: "Oberbalm" },
        { id: 358, name: "FBE" },
        { id: 359, name: "Vechigen" },
        { id: 360, name: "Wohlen bei Bern" },
        { id: 361, name: "Zollikofen" },
        { id: 362, name: "Ittigen" },
        { id: 363, name: "Ostermundigen" },
        { id: 371, name: "Biel/Bienne" },
        { id: 372, name: "Evilard" },
        { id: 381, name: "Arch" },
        { id: 382, name: "Büetigen" },
        { id: 383, name: "Büren an der Aare" },
        { id: 385, name: "Diessbach bei Büren" },
        { id: 386, name: "Dotzigen" },
        { id: 387, name: "Lengnau (BE)" },
        { id: 388, name: "Leuzigen" },
        { id: 389, name: "Meienried" },
        { id: 390, name: "Meinisberg" },
        { id: 391, name: "Oberwil bei Büren" },
        { id: 392, name: "Pieterlen" },
        { id: 393, name: "Rüti bei Büren" },
        { id: 394, name: "Wengi" },
        { id: 401, name: "Aefligen" },
        { id: 402, name: "Alchenstorf" },
        { id: 403, name: "Bäriswil" },
        { id: 404, name: "Burgdorf" },
        { id: 405, name: "Ersigen" },
        { id: 406, name: "Hasle bei Burgdorf" },
        { id: 407, name: "Heimiswil" },
        { id: 408, name: "Hellsau" },
        { id: 409, name: "Hindelbank" },
        { id: 410, name: "Höchstetten" },
        { id: 411, name: "Kernenried" },
        { id: 412, name: "Kirchberg (BE)" },
        { id: 413, name: "Koppigen" },
        { id: 414, name: "Krauchthal" },
        { id: 415, name: "Lyssach" },
        { id: 418, name: "Oberburg" },
        { id: 420, name: "Rüdtligen-Alchenflüh" },
        { id: 421, name: "Rumendingen" },
        { id: 422, name: "Rüti bei Lyssach" },
        { id: 423, name: "Willadingen" },
        { id: 424, name: "Wynigen" },
        { id: 431, name: "Corgémont" },
        { id: 432, name: "Cormoret" },
        { id: 433, name: "Cortébert" },
        { id: 434, name: "Courtelary" },
        { id: 435, name: "La Ferrière" },
        { id: 437, name: "Mont-Tramelan" },
        { id: 438, name: "Orvin" },
        { id: 441, name: "Renan (BE)" },
        { id: 442, name: "Romont (BE)" },
        { id: 443, name: "Saint-Imier" },
        { id: 444, name: "Sonceboz-Sombeval" },
        { id: 445, name: "Sonvilier" },
        { id: 446, name: "Tramelan" },
        { id: 448, name: "Villeret" },
        { id: 449, name: "Sauge" },
        { id: 450, name: "Péry-La Heutte" },
        { id: 491, name: "Brüttelen" },
        { id: 492, name: "Erlach" },
        { id: 493, name: "Finsterhennen" },
        { id: 494, name: "Gals" },
        { id: 495, name: "Gampelen" },
        { id: 496, name: "Ins" },
        { id: 497, name: "Lüscherz" },
        { id: 498, name: "Müntschemier" },
        { id: 499, name: "Siselen" },
        { id: 500, name: "Treiten" },
        { id: 501, name: "Tschugg" },
        { id: 502, name: "Vinelz" },
        { id: 533, name: "Bätterkinden" },
        { id: 535, name: "Deisswil bei Münchenbuchsee" },
        { id: 536, name: "Diemerswil" },
        { id: 538, name: "Fraubrunnen" },
        { id: 540, name: "Jegenstorf" },
        { id: 541, name: "Iffwil" },
        { id: 543, name: "Mattstetten" },
        { id: 544, name: "Moosseedorf" },
        { id: 546, name: "Münchenbuchsee" },
        { id: 551, name: "Urtenen-Schönbühl" },
        { id: 552, name: "Utzenstorf" },
        { id: 553, name: "Wiggiswil" },
        { id: 554, name: "Wiler bei Utzenstorf" },
        { id: 556, name: "Zielebach" },
        { id: 557, name: "Zuzwil (BE)" },
        { id: 561, name: "Adelboden" },
        { id: 562, name: "Aeschi bei Spiez" },
        { id: 563, name: "Frutigen" },
        { id: 564, name: "Kandergrund" },
        { id: 565, name: "Kandersteg" },
        { id: 566, name: "Krattigen" },
        { id: 567, name: "Reichenbach im Kandertal" },
        { id: 571, name: "Beatenberg" },
        { id: 572, name: "Bönigen" },
        { id: 573, name: "Brienz (BE)" },
        { id: 574, name: "Brienzwiler" },
        { id: 575, name: "Därligen" },
        { id: 576, name: "Grindelwald" },
        { id: 577, name: "Gsteigwiler" },
        { id: 578, name: "Gündlischwand" },
        { id: 579, name: "Habkern" },
        { id: 580, name: "Hofstetten bei Brienz" },
        { id: 581, name: "Interlaken" },
        { id: 582, name: "Iseltwald" },
        { id: 584, name: "Lauterbrunnen" },
        { id: 585, name: "Leissigen" },
        { id: 586, name: "Lütschental" },
        { id: 587, name: "Matten bei Interlaken" },
        { id: 588, name: "Niederried bei Interlaken" },
        { id: 589, name: "Oberried am Brienzersee" },
        { id: 590, name: "Ringgenberg (BE)" },
        { id: 591, name: "Saxeten" },
        { id: 592, name: "Schwanden bei Brienz" },
        { id: 593, name: "Unterseen" },
        { id: 594, name: "Wilderswil" },
        { id: 602, name: "Arni (BE)" },
        { id: 603, name: "Biglen" },
        { id: 605, name: "Bowil" },
        { id: 606, name: "Brenzikofen" },
        { id: 607, name: "Freimettigen" },
        { id: 608, name: "Grosshöchstetten" },
        { id: 609, name: "Häutligen" },
        { id: 610, name: "Herbligen" },
        { id: 611, name: "Kiesen" },
        { id: 612, name: "Konolfingen" },
        { id: 613, name: "Landiswil" },
        { id: 614, name: "Linden" },
        { id: 615, name: "Mirchel" },
        { id: 616, name: "Münsingen" },
        { id: 617, name: "Niederhünigen" },
        { id: 619, name: "Oberdiessbach" },
        { id: 620, name: "Oberthal" },
        { id: 622, name: "Oppligen" },
        { id: 623, name: "Rubigen" },
        { id: 626, name: "Walkringen" },
        { id: 627, name: "Worb" },
        { id: 628, name: "Zäziwil" },
        { id: 629, name: "Oberhünigen" },
        { id: 630, name: "Allmendingen" },
        { id: 632, name: "Wichtrach" },
        { id: 661, name: "Clavaleyres" },
        { id: 662, name: "Ferenbalm" },
        { id: 663, name: "Frauenkappelen" },
        { id: 665, name: "Gurbrü" },
        { id: 666, name: "Kriechenwil" },
        { id: 667, name: "Laupen" },
        { id: 668, name: "Mühleberg" },
        { id: 669, name: "Münchenwiler" },
        { id: 670, name: "Neuenegg" },
        { id: 671, name: "Wileroltigen" },
        { id: 681, name: "Belprahon" },
        { id: 683, name: "Champoz" },
        { id: 687, name: "Corcelles (BE)" },
        { id: 690, name: "Court" },
        { id: 691, name: "Crémines" },
        { id: 692, name: "Eschert" },
        { id: 694, name: "Grandval" },
        { id: 696, name: "Loveresse" },
        { id: 700, name: "Moutier" },
        { id: 701, name: "Perrefitte" },
        { id: 703, name: "Reconvilier" },
        { id: 704, name: "Roches (BE)" },
        { id: 706, name: "Saicourt" },
        { id: 707, name: "Saules (BE)" },
        { id: 708, name: "Schelten" },
        { id: 709, name: "Seehof" },
        { id: 711, name: "Sorvilier" },
        { id: 713, name: "Tavannes" },
        { id: 715, name: "Rebévelier" },
        { id: 716, name: "Petit-Val" },
        { id: 717, name: "Valbirse" },
        { id: 723, name: "La Neuveville" },
        { id: 724, name: "Nods" },
        { id: 726, name: "Plateau de Diesse" },
        { id: 731, name: "Aegerten" },
        { id: 732, name: "Bellmund" },
        { id: 733, name: "Brügg" },
        { id: 734, name: "Bühl" },
        { id: 735, name: "Epsach" },
        { id: 736, name: "Hagneck" },
        { id: 737, name: "Hermrigen" },
        { id: 738, name: "Jens" },
        { id: 739, name: "Ipsach" },
        { id: 740, name: "Ligerz" },
        { id: 741, name: "Merzligen" },
        { id: 742, name: "Mörigen" },
        { id: 743, name: "Nidau" },
        { id: 744, name: "Orpund" },
        { id: 745, name: "Port" },
        { id: 746, name: "Safnern" },
        { id: 747, name: "Scheuren" },
        { id: 748, name: "Schwadernau" },
        { id: 749, name: "Studen (BE)" },
        { id: 750, name: "Sutz-Lattrigen" },
        { id: 751, name: "Täuffelen" },
        { id: 754, name: "Walperswil" },
        { id: 755, name: "Worben" },
        { id: 756, name: "Twann-Tüscherz" },
        { id: 761, name: "Därstetten" },
        { id: 762, name: "Diemtigen" },
        { id: 763, name: "Erlenbach im Simmental" },
        { id: 766, name: "Oberwil im Simmental" },
        { id: 767, name: "Reutigen" },
        { id: 768, name: "Spiez" },
        { id: 769, name: "Wimmis" },
        { id: 770, name: "Stocken-Höfen" },
        { id: 782, name: "Guttannen" },
        { id: 783, name: "Hasliberg" },
        { id: 784, name: "Innertkirchen" },
        { id: 785, name: "Meiringen" },
        { id: 786, name: "Schattenhalb" },
        { id: 791, name: "Boltigen" },
        { id: 792, name: "Lenk" },
        { id: 793, name: "St. Stephan" },
        { id: 794, name: "Zweisimmen" },
        { id: 841, name: "Gsteig" },
        { id: 842, name: "Lauenen" },
        { id: 843, name: "Saanen" },
        { id: 852, name: "Guggisberg" },
        { id: 853, name: "Rüschegg" },
        { id: 855, name: "Schwarzenburg" },
        { id: 861, name: "Belp" },
        { id: 863, name: "Burgistein" },
        { id: 866, name: "Gerzensee" },
        { id: 867, name: "Gurzelen" },
        { id: 868, name: "Jaberg" },
        { id: 869, name: "Kaufdorf" },
        { id: 870, name: "Kehrsatz" },
        { id: 872, name: "Kirchdorf (BE)" },
        { id: 877, name: "Niedermuhlern" },
        { id: 879, name: "Riggisberg" },
        { id: 880, name: "Rüeggisberg" },
        { id: 883, name: "Seftigen" },
        { id: 884, name: "Toffen" },
        { id: 885, name: "Uttigen" },
        { id: 886, name: "Wattenwil" },
        { id: 888, name: "Wald (BE)" },
        { id: 889, name: "Thurnen" },
        { id: 901, name: "Eggiwil" },
        { id: 902, name: "Langnau im Emmental" },
        { id: 903, name: "Lauperswil" },
        { id: 904, name: "Röthenbach im Emmental" },
        { id: 905, name: "Rüderswil" },
        { id: 906, name: "Schangnau" },
        { id: 907, name: "Signau" },
        { id: 908, name: "Trub" },
        { id: 909, name: "Trubschachen" },
        { id: 921, name: "Amsoldingen" },
        { id: 922, name: "Blumenstein" },
        { id: 923, name: "Buchholterberg" },
        { id: 924, name: "Eriz" },
        { id: 925, name: "Fahrni" },
        { id: 927, name: "Heiligenschwendi" },
        { id: 928, name: "Heimberg" },
        { id: 929, name: "Hilterfingen" },
        { id: 931, name: "Homberg" },
        { id: 932, name: "Horrenbach-Buchen" },
        { id: 934, name: "Oberhofen am Thunersee" },
        { id: 935, name: "Oberlangenegg" },
        { id: 936, name: "Pohlern" },
        { id: 938, name: "Sigriswil" },
        { id: 939, name: "Steffisburg" },
        { id: 940, name: "Teuffenthal (BE)" },
        { id: 941, name: "Thierachern" },
        { id: 942, name: "Thun" },
        { id: 943, name: "Uebeschi" },
        { id: 944, name: "Uetendorf" },
        { id: 945, name: "Unterlangenegg" },
        { id: 946, name: "Wachseldorn" },
        { id: 947, name: "Zwieselberg" },
        { id: 948, name: "Forst-Längenbühl" },
        { id: 951, name: "Affoltern im Emmental" },
        { id: 952, name: "Dürrenroth" },
        { id: 953, name: "Eriswil" },
        { id: 954, name: "Huttwil" },
        { id: 955, name: "Lützelflüh" },
        { id: 956, name: "Rüegsau" },
        { id: 957, name: "Sumiswald" },
        { id: 958, name: "Trachselwald" },
        { id: 959, name: "Walterswil (BE)" },
        { id: 960, name: "Wyssachen" },
        { id: 971, name: "Attiswil" },
        { id: 972, name: "Berken" },
        { id: 973, name: "Bettenhausen" },
        { id: 975, name: "Farnern" },
        { id: 976, name: "Graben" },
        { id: 977, name: "Heimenhausen" },
        { id: 979, name: "Herzogenbuchsee" },
        { id: 980, name: "Inkwil" },
        { id: 981, name: "Niederbipp" },
        { id: 982, name: "Niederönz" },
        { id: 983, name: "Oberbipp" },
        { id: 985, name: "Ochlenberg" },
        { id: 987, name: "Rumisberg" },
        { id: 988, name: "Seeberg" },
        { id: 989, name: "Thörigen" },
        { id: 990, name: "Walliswil bei Niederbipp" },
        { id: 991, name: "Walliswil bei Wangen" },
        { id: 992, name: "Wangen an der Aare" },
        { id: 993, name: "Wangenried" },
        { id: 995, name: "Wiedlisbach" },
      ],
      UR: [
        { id: 1201, name: "Altdorf (UR)" },
        { id: 1202, name: "Andermatt" },
        { id: 1203, name: "Attinghausen" },
        { id: 1205, name: "Bürglen (UR)" },
        { id: 1206, name: "Erstfeld" },
        { id: 1207, name: "Flüelen" },
        { id: 1208, name: "Göschenen" },
        { id: 1209, name: "Gurtnellen" },
        { id: 1210, name: "Hospental" },
        { id: 1211, name: "Isenthal" },
        { id: 1212, name: "Realp" },
        { id: 1213, name: "Schattdorf" },
        { id: 1214, name: "Seedorf (UR)" },
        { id: 1215, name: "Seelisberg" },
        { id: 1216, name: "Silenen" },
        { id: 1217, name: "Sisikon" },
        { id: 1218, name: "Spiringen" },
        { id: 1219, name: "Unterschächen" },
        { id: 1220, name: "Wassen" },
      ],
    },
  };

  return ENV;
};
