export default {
  SO: [
    { id: 2401, name: "Egerkingen" },
    { id: 2402, name: "Härkingen" },
    { id: 2403, name: "Kestenholz" },
    { id: 2404, name: "Neuendorf" },
    { id: 2405, name: "Niederbuchsiten" },
    { id: 2406, name: "Oberbuchsiten" },
    { id: 2407, name: "Oensingen" },
    { id: 2408, name: "Wolfwil" },
    { id: 2421, name: "Aedermannsdorf" },
    { id: 2422, name: "Balsthal" },
    { id: 2424, name: "Herbetswil" },
    { id: 2425, name: "Holderbank (SO)" },
    { id: 2426, name: "Laupersdorf" },
    { id: 2427, name: "Matzendorf" },
    { id: 2428, name: "Mümliswil-Ramiswil" },
    { id: 2430, name: "Welschenrohr-Gänsbrunnen" },
    { id: 2445, name: "Biezwil" },
    { id: 2455, name: "Lüterkofen-Ichertswil" },
    { id: 2457, name: "Messen" },
    { id: 2461, name: "Schnottwil" },
    { id: 2463, name: "Unterramsern" },
    { id: 2464, name: "Lüsslingen-Nennigkofen" },
    { id: 2465, name: "Buchegg" },
    { id: 2471, name: "Bättwil" },
    { id: 2472, name: "Büren (SO)" },
    { id: 2473, name: "Dornach" },
    { id: 2474, name: "Gempen" },
    { id: 2475, name: "Hochwald" },
    { id: 2476, name: "Hofstetten-Flüh" },
    { id: 2477, name: "Metzerlen-Mariastein" },
    { id: 2478, name: "Nuglar-St. Pantaleon" },
    { id: 2479, name: "Rodersdorf" },
    { id: 2480, name: "Seewen" },
    { id: 2481, name: "Witterswil" },
    { id: 2491, name: "Hauenstein-Ifenthal" },
    { id: 2492, name: "Kienberg" },
    { id: 2493, name: "Lostorf" },
    { id: 2495, name: "Niedergösgen" },
    { id: 2497, name: "Obergösgen" },
    { id: 2499, name: "Stüsslingen" },
    { id: 2500, name: "Trimbach" },
    { id: 2501, name: "Winznau" },
    { id: 2502, name: "Wisen (SO)" },
    { id: 2503, name: "Erlinsbach (SO)" },
    { id: 2511, name: "Aeschi (SO)" },
    { id: 2513, name: "Biberist" },
    { id: 2514, name: "Bolken" },
    { id: 2516, name: "Deitingen" },
    { id: 2517, name: "Derendingen" },
    { id: 2518, name: "Etziken" },
    { id: 2519, name: "Gerlafingen" },
    { id: 2520, name: "Halten" },
    { id: 2523, name: "Horriwil" },
    { id: 2524, name: "Hüniken" },
    { id: 2525, name: "Kriegstetten" },
    { id: 2526, name: "Lohn-Ammannsegg" },
    { id: 2527, name: "Luterbach" },
    { id: 2528, name: "Obergerlafingen" },
    { id: 2529, name: "Oekingen" },
    { id: 2530, name: "Recherswil" },
    { id: 2532, name: "Subingen" },
    { id: 2534, name: "Zuchwil" },
    { id: 2535, name: "Drei Höfe" },
    { id: 2541, name: "Balm bei Günsberg" },
    { id: 2542, name: "Bellach" },
    { id: 2543, name: "Bettlach" },
    { id: 2544, name: "Feldbrunnen-St. Niklaus" },
    { id: 2545, name: "Flumenthal" },
    { id: 2546, name: "Grenchen" },
    { id: 2547, name: "Günsberg" },
    { id: 2548, name: "Hubersdorf" },
    { id: 2549, name: "Kammersrohr" },
    { id: 2550, name: "Langendorf" },
    { id: 2551, name: "Lommiswil" },
    { id: 2553, name: "Oberdorf (SO)" },
    { id: 2554, name: "Riedholz" },
    { id: 2555, name: "Rüttenen" },
    { id: 2556, name: "Selzach" },
    { id: 2571, name: "Boningen" },
    { id: 2572, name: "Däniken" },
    { id: 2573, name: "Dulliken" },
    { id: 2574, name: "Eppenberg-Wöschnau" },
    { id: 2575, name: "Fulenbach" },
    { id: 2576, name: "Gretzenbach" },
    { id: 2578, name: "Gunzgen" },
    { id: 2579, name: "Hägendorf" },
    { id: 2580, name: "Kappel (SO)" },
    { id: 2581, name: "Olten" },
    { id: 2582, name: "Rickenbach (SO)" },
    { id: 2583, name: "Schönenwerd" },
    { id: 2584, name: "Starrkirch-Wil" },
    { id: 2585, name: "Walterswil (SO)" },
    { id: 2586, name: "Wangen bei Olten" },
    { id: 2601, name: "Solothurn" },
    { id: 2611, name: "Bärschwil" },
    { id: 2612, name: "Beinwil (SO)" },
    { id: 2613, name: "Breitenbach" },
    { id: 2614, name: "Büsserach" },
    { id: 2615, name: "Erschwil" },
    { id: 2616, name: "Fehren" },
    { id: 2617, name: "Grindel" },
    { id: 2618, name: "Himmelried" },
    { id: 2619, name: "Kleinlützel" },
    { id: 2620, name: "Meltingen" },
    { id: 2621, name: "Nunningen" },
    { id: 2622, name: "Zullwil" },
  ],
  GR: [
    { id: 3506, name: "Vaz/Obervaz" },
    { id: 3513, name: "Lantsch/Lenz" },
    { id: 3514, name: "Schmitten (GR)" },
    { id: 3542, name: "Albula/Alvra" },
    { id: 3543, name: "Surses" },
    { id: 3544, name: "Bergün Filisur" },
    { id: 3551, name: "Brusio" },
    { id: 3561, name: "Poschiavo" },
    { id: 3572, name: "Falera" },
    { id: 3575, name: "Laax" },
    { id: 3581, name: "Sagogn" },
    { id: 3582, name: "Schluein" },
    { id: 3603, name: "Vals" },
    { id: 3618, name: "Lumnezia" },
    { id: 3619, name: "Ilanz/Glion" },
    { id: 3633, name: "Fürstenau" },
    { id: 3637, name: "Rothenbrunnen" },
    { id: 3638, name: "Scharans" },
    { id: 3640, name: "Sils im Domleschg" },
    { id: 3661, name: "Cazis" },
    { id: 3662, name: "Flerden" },
    { id: 3663, name: "Masein" },
    { id: 3668, name: "Thusis" },
    { id: 3669, name: "Tschappina" },
    { id: 3670, name: "Urmein" },
    { id: 3672, name: "Safiental" },
    { id: 3673, name: "Domleschg" },
    { id: 3681, name: "Avers" },
    { id: 3695, name: "Sufers" },
    { id: 3701, name: "Andeer" },
    { id: 3711, name: "Rongellen" },
    { id: 3712, name: "Zillis-Reischen" },
    { id: 3713, name: "Ferrera" },
    { id: 3714, name: "Rheinwald" },
    { id: 3715, name: "Muntogna da Schons" },
    { id: 3721, name: "Bonaduz" },
    { id: 3722, name: "Domat/Ems" },
    { id: 3723, name: "Rhäzüns" },
    { id: 3731, name: "Felsberg" },
    { id: 3732, name: "Flims" },
    { id: 3733, name: "Tamins" },
    { id: 3734, name: "Trin" },
    { id: 3746, name: "Zernez" },
    { id: 3752, name: "Samnaun" },
    { id: 3762, name: "Scuol" },
    { id: 3764, name: "Valsot" },
    { id: 3781, name: "Bever" },
    { id: 3782, name: "Celerina/Schlarigna" },
    { id: 3783, name: "Madulain" },
    { id: 3784, name: "Pontresina" },
    { id: 3785, name: "La Punt Chamues-ch" },
    { id: 3786, name: "Samedan" },
    { id: 3787, name: "St. Moritz" },
    { id: 3788, name: "S-chanf" },
    { id: 3789, name: "Sils im Engadin/Segl" },
    { id: 3790, name: "Silvaplana" },
    { id: 3791, name: "Zuoz" },
    { id: 3792, name: "Bregaglia" },
    { id: 3804, name: "Buseno" },
    { id: 3805, name: "Castaneda" },
    { id: 3808, name: "Rossa" },
    { id: 3810, name: "Santa Maria in Calanca" },
    { id: 3821, name: "Lostallo" },
    { id: 3822, name: "Mesocco" },
    { id: 3823, name: "Soazza" },
    { id: 3831, name: "Cama" },
    { id: 3832, name: "Grono" },
    { id: 3834, name: "Roveredo (GR)" },
    { id: 3835, name: "San Vittore" },
    { id: 3837, name: "Calanca" },
    { id: 3847, name: "Val Müstair" },
    { id: 3851, name: "Davos" },
    { id: 3861, name: "Fideris" },
    { id: 3862, name: "Furna" },
    { id: 3863, name: "Jenaz" },
    { id: 3871, name: "Klosters" },
    { id: 3881, name: "Conters im Prättigau" },
    { id: 3882, name: "Küblis" },
    { id: 3891, name: "Luzein" },
    { id: 3901, name: "Chur" },
    { id: 3911, name: "Churwalden" },
    { id: 3921, name: "Arosa" },
    { id: 3932, name: "Tschiertschen-Praden" },
    { id: 3945, name: "Trimmis" },
    { id: 3946, name: "Untervaz" },
    { id: 3947, name: "Zizers" },
    { id: 3951, name: "Fläsch" },
    { id: 3952, name: "Jenins" },
    { id: 3953, name: "Maienfeld" },
    { id: 3954, name: "Malans" },
    { id: 3955, name: "Landquart" },
    { id: 3961, name: "Grüsch" },
    { id: 3962, name: "Schiers" },
    { id: 3972, name: "Seewis im Prättigau" },
    { id: 3981, name: "Breil/Brigels" },
    { id: 3982, name: "Disentis/Mustér" },
    { id: 3983, name: "Medel (Lucmagn)" },
    { id: 3985, name: "Sumvitg" },
    { id: 3986, name: "Tujetsch" },
    { id: 3987, name: "Trun" },
    { id: 3988, name: "Obersaxen Mundaun" },
  ],
  SZ: [
    { id: 1311, name: "Gersau" },
    { id: 1321, name: "Feusisberg" },
    { id: 1322, name: "Freienbach" },
    { id: 1323, name: "Wollerau" },
    { id: 1331, name: "Küssnacht (SZ)" },
    { id: 1341, name: "Altendorf" },
    { id: 1342, name: "Galgenen" },
    { id: 1343, name: "Innerthal" },
    { id: 1344, name: "Lachen" },
    { id: 1345, name: "Reichenburg" },
    { id: 1346, name: "Schübelbach" },
    { id: 1347, name: "Tuggen" },
    { id: 1348, name: "Vorderthal" },
    { id: 1349, name: "Wangen (SZ)" },
    { id: 1361, name: "Alpthal" },
    { id: 1362, name: "Arth" },
    { id: 1363, name: "Illgau" },
    { id: 1364, name: "Ingenbohl" },
    { id: 1365, name: "Lauerz" },
    { id: 1366, name: "Morschach" },
    { id: 1367, name: "Muotathal" },
    { id: 1368, name: "Oberiberg" },
    { id: 1369, name: "Riemenstalden" },
    { id: 1370, name: "Rothenthurm" },
    { id: 1371, name: "Sattel" },
    { id: 1372, name: "Schwyz" },
    { id: 1373, name: "Steinen" },
    { id: 1374, name: "Steinerberg" },
    { id: 1375, name: "Unteriberg" },
  ],
  BE: [
    { id: 301, name: "Aarberg" },
    { id: 302, name: "Bargen (BE)" },
    { id: 303, name: "Grossaffoltern" },
    { id: 304, name: "Kallnach" },
    { id: 305, name: "Kappelen" },
    { id: 306, name: "Lyss" },
    { id: 307, name: "Meikirch" },
    { id: 309, name: "Radelfingen" },
    { id: 310, name: "Rapperswil (BE)" },
    { id: 311, name: "Schüpfen" },
    { id: 312, name: "Seedorf (BE)" },
    { id: 321, name: "Aarwangen" },
    { id: 322, name: "Auswil" },
    { id: 323, name: "Bannwil" },
    { id: 324, name: "Bleienbach" },
    { id: 325, name: "Busswil bei Melchnau" },
    { id: 326, name: "Gondiswil" },
    { id: 329, name: "Langenthal" },
    { id: 331, name: "Lotzwil" },
    { id: 332, name: "Madiswil" },
    { id: 333, name: "Melchnau" },
    { id: 335, name: "Oeschenbach" },
    { id: 336, name: "Reisiswil" },
    { id: 337, name: "Roggwil (BE)" },
    { id: 338, name: "Rohrbach" },
    { id: 339, name: "Rohrbachgraben" },
    { id: 340, name: "Rütschelen" },
    { id: 341, name: "Schwarzhäusern" },
    { id: 342, name: "Thunstetten" },
    { id: 344, name: "Ursenbach" },
    { id: 345, name: "Wynau" },
    { id: 351, name: "Bern" },
    { id: 352, name: "Bolligen" },
    { id: 353, name: "Bremgarten bei Bern" },
    { id: 354, name: "Kirchlindach" },
    { id: 355, name: "Köniz" },
    { id: 356, name: "Muri bei Bern" },
    { id: 357, name: "Oberbalm" },
    { id: 358, name: "Stettlen" },
    { id: 359, name: "Vechigen" },
    { id: 360, name: "Wohlen bei Bern" },
    { id: 361, name: "Zollikofen" },
    { id: 362, name: "Ittigen" },
    { id: 363, name: "Ostermundigen" },
    { id: 371, name: "Biel/Bienne" },
    { id: 372, name: "Evilard" },
    { id: 381, name: "Arch" },
    { id: 382, name: "Büetigen" },
    { id: 383, name: "Büren an der Aare" },
    { id: 385, name: "Diessbach bei Büren" },
    { id: 386, name: "Dotzigen" },
    { id: 387, name: "Lengnau (BE)" },
    { id: 388, name: "Leuzigen" },
    { id: 389, name: "Meienried" },
    { id: 390, name: "Meinisberg" },
    { id: 391, name: "Oberwil bei Büren" },
    { id: 392, name: "Pieterlen" },
    { id: 393, name: "Rüti bei Büren" },
    { id: 394, name: "Wengi" },
    { id: 401, name: "Aefligen" },
    { id: 402, name: "Alchenstorf" },
    { id: 403, name: "Bäriswil" },
    { id: 404, name: "Burgdorf" },
    { id: 405, name: "Ersigen" },
    { id: 406, name: "Hasle bei Burgdorf" },
    { id: 407, name: "Heimiswil" },
    { id: 408, name: "Hellsau" },
    { id: 409, name: "Hindelbank" },
    { id: 410, name: "Höchstetten" },
    { id: 411, name: "Kernenried" },
    { id: 412, name: "Kirchberg (BE)" },
    { id: 413, name: "Koppigen" },
    { id: 414, name: "Krauchthal" },
    { id: 415, name: "Lyssach" },
    { id: 418, name: "Oberburg" },
    { id: 420, name: "Rüdtligen-Alchenflüh" },
    { id: 421, name: "Rumendingen" },
    { id: 422, name: "Rüti bei Lyssach" },
    { id: 423, name: "Willadingen" },
    { id: 424, name: "Wynigen" },
    { id: 431, name: "Corgémont" },
    { id: 432, name: "Cormoret" },
    { id: 433, name: "Cortébert" },
    { id: 434, name: "Courtelary" },
    { id: 435, name: "La Ferrière" },
    { id: 437, name: "Mont-Tramelan" },
    { id: 438, name: "Orvin" },
    { id: 441, name: "Renan (BE)" },
    { id: 442, name: "Romont (BE)" },
    { id: 443, name: "Saint-Imier" },
    { id: 444, name: "Sonceboz-Sombeval" },
    { id: 445, name: "Sonvilier" },
    { id: 446, name: "Tramelan" },
    { id: 448, name: "Villeret" },
    { id: 449, name: "Sauge" },
    { id: 450, name: "Péry-La Heutte" },
    { id: 491, name: "Brüttelen" },
    { id: 492, name: "Erlach" },
    { id: 493, name: "Finsterhennen" },
    { id: 494, name: "Gals" },
    { id: 495, name: "Gampelen" },
    { id: 496, name: "Ins" },
    { id: 497, name: "Lüscherz" },
    { id: 498, name: "Müntschemier" },
    { id: 499, name: "Siselen" },
    { id: 500, name: "Treiten" },
    { id: 501, name: "Tschugg" },
    { id: 502, name: "Vinelz" },
    { id: 533, name: "Bätterkinden" },
    { id: 535, name: "Deisswil bei Münchenbuchsee" },
    { id: 536, name: "Diemerswil" },
    { id: 538, name: "Fraubrunnen" },
    { id: 540, name: "Jegenstorf" },
    { id: 541, name: "Iffwil" },
    { id: 543, name: "Mattstetten" },
    { id: 544, name: "Moosseedorf" },
    { id: 546, name: "Münchenbuchsee" },
    { id: 551, name: "Urtenen-Schönbühl" },
    { id: 552, name: "Utzenstorf" },
    { id: 553, name: "Wiggiswil" },
    { id: 554, name: "Wiler bei Utzenstorf" },
    { id: 556, name: "Zielebach" },
    { id: 557, name: "Zuzwil (BE)" },
    { id: 561, name: "Adelboden" },
    { id: 562, name: "Aeschi bei Spiez" },
    { id: 563, name: "Frutigen" },
    { id: 564, name: "Kandergrund" },
    { id: 565, name: "Kandersteg" },
    { id: 566, name: "Krattigen" },
    { id: 567, name: "Reichenbach im Kandertal" },
    { id: 571, name: "Beatenberg" },
    { id: 572, name: "Bönigen" },
    { id: 573, name: "Brienz (BE)" },
    { id: 574, name: "Brienzwiler" },
    { id: 575, name: "Därligen" },
    { id: 576, name: "Grindelwald" },
    { id: 577, name: "Gsteigwiler" },
    { id: 578, name: "Gündlischwand" },
    { id: 579, name: "Habkern" },
    { id: 580, name: "Hofstetten bei Brienz" },
    { id: 581, name: "Interlaken" },
    { id: 582, name: "Iseltwald" },
    { id: 584, name: "Lauterbrunnen" },
    { id: 585, name: "Leissigen" },
    { id: 586, name: "Lütschental" },
    { id: 587, name: "Matten bei Interlaken" },
    { id: 588, name: "Niederried bei Interlaken" },
    { id: 589, name: "Oberried am Brienzersee" },
    { id: 590, name: "Ringgenberg (BE)" },
    { id: 591, name: "Saxeten" },
    { id: 592, name: "Schwanden bei Brienz" },
    { id: 593, name: "Unterseen" },
    { id: 594, name: "Wilderswil" },
    { id: 602, name: "Arni (BE)" },
    { id: 603, name: "Biglen" },
    { id: 605, name: "Bowil" },
    { id: 606, name: "Brenzikofen" },
    { id: 607, name: "Freimettigen" },
    { id: 608, name: "Grosshöchstetten" },
    { id: 609, name: "Häutligen" },
    { id: 610, name: "Herbligen" },
    { id: 611, name: "Kiesen" },
    { id: 612, name: "Konolfingen" },
    { id: 613, name: "Landiswil" },
    { id: 614, name: "Linden" },
    { id: 615, name: "Mirchel" },
    { id: 616, name: "Münsingen" },
    { id: 617, name: "Niederhünigen" },
    { id: 619, name: "Oberdiessbach" },
    { id: 620, name: "Oberthal" },
    { id: 622, name: "Oppligen" },
    { id: 623, name: "Rubigen" },
    { id: 626, name: "Walkringen" },
    { id: 627, name: "Worb" },
    { id: 628, name: "Zäziwil" },
    { id: 629, name: "Oberhünigen" },
    { id: 630, name: "Allmendingen" },
    { id: 632, name: "Wichtrach" },
    { id: 661, name: "Clavaleyres" },
    { id: 662, name: "Ferenbalm" },
    { id: 663, name: "Frauenkappelen" },
    { id: 665, name: "Gurbrü" },
    { id: 666, name: "Kriechenwil" },
    { id: 667, name: "Laupen" },
    { id: 668, name: "Mühleberg" },
    { id: 669, name: "Münchenwiler" },
    { id: 670, name: "Neuenegg" },
    { id: 671, name: "Wileroltigen" },
    { id: 681, name: "Belprahon" },
    { id: 683, name: "Champoz" },
    { id: 687, name: "Corcelles (BE)" },
    { id: 690, name: "Court" },
    { id: 691, name: "Crémines" },
    { id: 692, name: "Eschert" },
    { id: 694, name: "Grandval" },
    { id: 696, name: "Loveresse" },
    { id: 700, name: "Moutier" },
    { id: 701, name: "Perrefitte" },
    { id: 703, name: "Reconvilier" },
    { id: 704, name: "Roches (BE)" },
    { id: 706, name: "Saicourt" },
    { id: 707, name: "Saules (BE)" },
    { id: 708, name: "Schelten" },
    { id: 709, name: "Seehof" },
    { id: 711, name: "Sorvilier" },
    { id: 713, name: "Tavannes" },
    { id: 715, name: "Rebévelier" },
    { id: 716, name: "Petit-Val" },
    { id: 717, name: "Valbirse" },
    { id: 723, name: "La Neuveville" },
    { id: 724, name: "Nods" },
    { id: 726, name: "Plateau de Diesse" },
    { id: 731, name: "Aegerten" },
    { id: 732, name: "Bellmund" },
    { id: 733, name: "Brügg" },
    { id: 734, name: "Bühl" },
    { id: 735, name: "Epsach" },
    { id: 736, name: "Hagneck" },
    { id: 737, name: "Hermrigen" },
    { id: 738, name: "Jens" },
    { id: 739, name: "Ipsach" },
    { id: 740, name: "Ligerz" },
    { id: 741, name: "Merzligen" },
    { id: 742, name: "Mörigen" },
    { id: 743, name: "Nidau" },
    { id: 744, name: "Orpund" },
    { id: 745, name: "Port" },
    { id: 746, name: "Safnern" },
    { id: 747, name: "Scheuren" },
    { id: 748, name: "Schwadernau" },
    { id: 749, name: "Studen (BE)" },
    { id: 750, name: "Sutz-Lattrigen" },
    { id: 751, name: "Täuffelen" },
    { id: 754, name: "Walperswil" },
    { id: 755, name: "Worben" },
    { id: 756, name: "Twann-Tüscherz" },
    { id: 761, name: "Därstetten" },
    { id: 762, name: "Diemtigen" },
    { id: 763, name: "Erlenbach im Simmental" },
    { id: 766, name: "Oberwil im Simmental" },
    { id: 767, name: "Reutigen" },
    { id: 768, name: "Spiez" },
    { id: 769, name: "Wimmis" },
    { id: 770, name: "Stocken-Höfen" },
    { id: 782, name: "Guttannen" },
    { id: 783, name: "Hasliberg" },
    { id: 784, name: "Innertkirchen" },
    { id: 785, name: "Meiringen" },
    { id: 786, name: "Schattenhalb" },
    { id: 791, name: "Boltigen" },
    { id: 792, name: "Lenk" },
    { id: 793, name: "St. Stephan" },
    { id: 794, name: "Zweisimmen" },
    { id: 841, name: "Gsteig" },
    { id: 842, name: "Lauenen" },
    { id: 843, name: "Saanen" },
    { id: 852, name: "Guggisberg" },
    { id: 853, name: "Rüschegg" },
    { id: 855, name: "Schwarzenburg" },
    { id: 861, name: "Belp" },
    { id: 863, name: "Burgistein" },
    { id: 866, name: "Gerzensee" },
    { id: 867, name: "Gurzelen" },
    { id: 868, name: "Jaberg" },
    { id: 869, name: "Kaufdorf" },
    { id: 870, name: "Kehrsatz" },
    { id: 872, name: "Kirchdorf (BE)" },
    { id: 877, name: "Niedermuhlern" },
    { id: 879, name: "Riggisberg" },
    { id: 880, name: "Rüeggisberg" },
    { id: 883, name: "Seftigen" },
    { id: 884, name: "Toffen" },
    { id: 885, name: "Uttigen" },
    { id: 886, name: "Wattenwil" },
    { id: 888, name: "Wald (BE)" },
    { id: 889, name: "Thurnen" },
    { id: 901, name: "Eggiwil" },
    { id: 902, name: "Langnau im Emmental" },
    { id: 903, name: "Lauperswil" },
    { id: 904, name: "Röthenbach im Emmental" },
    { id: 905, name: "Rüderswil" },
    { id: 906, name: "Schangnau" },
    { id: 907, name: "Signau" },
    { id: 908, name: "Trub" },
    { id: 909, name: "Trubschachen" },
    { id: 921, name: "Amsoldingen" },
    { id: 922, name: "Blumenstein" },
    { id: 923, name: "Buchholterberg" },
    { id: 924, name: "Eriz" },
    { id: 925, name: "Fahrni" },
    { id: 927, name: "Heiligenschwendi" },
    { id: 928, name: "Heimberg" },
    { id: 929, name: "Hilterfingen" },
    { id: 931, name: "Homberg" },
    { id: 932, name: "Horrenbach-Buchen" },
    { id: 934, name: "Oberhofen am Thunersee" },
    { id: 935, name: "Oberlangenegg" },
    { id: 936, name: "Pohlern" },
    { id: 938, name: "Sigriswil" },
    { id: 939, name: "Steffisburg" },
    { id: 940, name: "Teuffenthal (BE)" },
    { id: 941, name: "Thierachern" },
    { id: 942, name: "Thun" },
    { id: 943, name: "Uebeschi" },
    { id: 944, name: "Uetendorf" },
    { id: 945, name: "Unterlangenegg" },
    { id: 946, name: "Wachseldorn" },
    { id: 947, name: "Zwieselberg" },
    { id: 948, name: "Forst-Längenbühl" },
    { id: 951, name: "Affoltern im Emmental" },
    { id: 952, name: "Dürrenroth" },
    { id: 953, name: "Eriswil" },
    { id: 954, name: "Huttwil" },
    { id: 955, name: "Lützelflüh" },
    { id: 956, name: "Rüegsau" },
    { id: 957, name: "Sumiswald" },
    { id: 958, name: "Trachselwald" },
    { id: 959, name: "Walterswil (BE)" },
    { id: 960, name: "Wyssachen" },
    { id: 971, name: "Attiswil" },
    { id: 972, name: "Berken" },
    { id: 973, name: "Bettenhausen" },
    { id: 975, name: "Farnern" },
    { id: 976, name: "Graben" },
    { id: 977, name: "Heimenhausen" },
    { id: 979, name: "Herzogenbuchsee" },
    { id: 980, name: "Inkwil" },
    { id: 981, name: "Niederbipp" },
    { id: 982, name: "Niederönz" },
    { id: 983, name: "Oberbipp" },
    { id: 985, name: "Ochlenberg" },
    { id: 987, name: "Rumisberg" },
    { id: 988, name: "Seeberg" },
    { id: 989, name: "Thörigen" },
    { id: 990, name: "Walliswil bei Niederbipp" },
    { id: 991, name: "Walliswil bei Wangen" },
    { id: 992, name: "Wangen an der Aare" },
    { id: 993, name: "Wangenried" },
    { id: 995, name: "Wiedlisbach" },
  ],
  UR: [
    { id: 1201, name: "Altdorf (UR)" },
    { id: 1202, name: "Andermatt" },
    { id: 1203, name: "Attinghausen" },
    { id: 1205, name: "Bürglen (UR)" },
    { id: 1206, name: "Erstfeld" },
    { id: 1207, name: "Flüelen" },
    { id: 1208, name: "Göschenen" },
    { id: 1209, name: "Gurtnellen" },
    { id: 1210, name: "Hospental" },
    { id: 1211, name: "Isenthal" },
    { id: 1212, name: "Realp" },
    { id: 1213, name: "Schattdorf" },
    { id: 1214, name: "Seedorf (UR)" },
    { id: 1215, name: "Seelisberg" },
    { id: 1216, name: "Silenen" },
    { id: 1217, name: "Sisikon" },
    { id: 1218, name: "Spiringen" },
    { id: 1219, name: "Unterschächen" },
    { id: 1220, name: "Wassen" },
  ],
};
